name: contrucción de imagen docker y packages

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalacion de requirements
        run: |
          pip install -r requirements.txt
          pip install pytest requests


      - name: inciar el servidor
        run: |
          nohup python main.py &

      - name: Ejecucion de las pruebas
        run: pytest Tests/ --maxfail=1 --disable-warnings -q


  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/enfermedad_predicha 
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest





