
permissions:
  pull-requests: write
  issues: write
  packages: write  ### necesario 

name: segundo evento  publicar la imagen docker buena

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3


      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests

      - name: inciar el servidor
        run: |
          nohup python main.py &

      - name: Ejecutar pruebas unitarias
        run: pytest Tests/ --maxfail=1 --disable-warnings -q


      - name: Publicar Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: 'diagnostico_completo'                    # Nombre que quieres para la imagen
          TAG: 'latest'                           # Etiqueta opcional (puedes poner el PR, commit, etc)
          DOCKERFILE_PATH: 'Dockerfile'           # Ruta al Dockerfile (ajusta si está en otra carpeta)
          BUILD_CONTEXT: '.'                      # Contexto de construcción (raíz del repo)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mostrar info de la imagen publicada (opcional)
        run: |
          echo "Imagen publicada: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}"
          echo "URL de la imagen: ${{ steps.docker.outputs.IMAGE_URL }}"