permissions:
  pull-requests: write
  issues: write

name: Comentar en Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comentar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias del sistema (build tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          


      - name: Comentar en el PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            CI/CD en acción. Ejecutando tareas …


