permissions:
  pull-requests: write
  issues: write

name: Comentar en Pull Request entre otros

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests

      - name: inciar el servidor
        run: |
          nohup python main.py &
          sleep5

      - name: Ejecutar pruebas unitarias
        run: pytest Tests/ --maxfail=1 --disable-warnings -q


